### ISSUE TITLE
When we click on the Pendants in the header navigation then the url is coming of charm.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/HSL-Home-page-design#1]
**Actual result:**
When we click on the Pendants in the header navigation then the url is coming of charm.
https://www.hsldiamonds.com/collections/charm
https://www.hsldiamonds.com/collections/ladies-rings
![image](https://user-images.githubusercontent.com/102131636/188565511-4c89afab-1441-4d27-a0a6-66f14fbf6c44.png)
![image](https://user-images.githubusercontent.com/102131636/188565945-85c42fc1-9ac8-4668-9313-3d3eb96c4f5a.png)

**Expected result:**
The handle needs to be updated on the url.

**Comment by dev-adityapatel** [comment]
@sudhanshu0603  done

**Comment by sudhanshu0603** [comment]
ok, resolved
