### ISSUE TITLE
In search page, when we search ring then the addtocart icon is not coming in search page but coming in collection pages.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/HSL-Home-page-design#10]
**Actual result:**
In search page, when we search ring then the addtocart icon is not coming in search page but coming in collection pages.
https://www.hsldiamonds.com/search?q=ring&options%5Bprefix%5D=last
![image](https://user-images.githubusercontent.com/102131636/188579599-e3a18fef-89c5-4d9e-b2a8-04a12fefea4e.png)
**Expected result:**
The cart icon have to come on the products on the search page.

**Comment by dev-adityapatel** [comment]
![image](https://user-images.githubusercontent.com/100192519/188802979-01b6d80f-bf04-4cf0-8b7f-fb7affd6d9f7.png)
@sudhanshu0603  resolved

**Comment by sudhanshu0603** [comment]
ok, resolved
