### ISSUE TITLE
In address page, when the phone number is starting from 0 then the error message is coming.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/HSL-Home-page-design#13]
**Actual result:**
In address page, when the phone number is starting from 0 then the error message is coming.
https://www.hsldiamonds.com/account/addresses
![image](https://user-images.githubusercontent.com/102131636/188584497-3602df07-6421-46f2-b150-60dc372615c6.png)

**Expected result:**
The phone number validation needed to be checked.

**Comment by dev-adityapatel** [comment]
@sudhanshu0603  resolved
