### ISSUE TITLE
In contact us form, when we are accepting the auto-suggestion phone number then the it is accepting the 0 as first but, by typing it is showing error.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/HSL-Home-page-design#14]
**Actual result:**
In contact us form, when we are accepting the auto-suggestion phone number then the it is accepting the 0 as first but, by typing it is showing error.
https://www.hsldiamonds.com/pages/contact
![image](https://user-images.githubusercontent.com/102131636/188585385-5e7c23c6-7f8b-40b3-a35f-a51b17a9bc08.png)

**Expected result:**
The phone number validation needs to be checked.

**Comment by dev-adityapatel** [comment]
@sudhanshu0603  Resolved now

**Comment by sudhanshu0603** [comment]
ok, resolved
