### ISSUE TITLE
In contact us form, when we fill the data by auto-suggestion then the when we hover over the send button then the form is not submitting.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/HSL-Home-page-design#15]
**Actual result:**
In contact us form, when we fill the data by auto-suggestion then the when we hover over the send button then the form is not submitting.
https://www.loom.com/share/7b8cdebb4ee94327ab43bc1a08d91cdc

**Expected result:**
The form should submit when we filll the data by autosuggestion.

**Comment by dev-adityapatel** [comment]
https://www.awesomescreenshot.com/video/10936184?key=873db0c5fbbf8124537515ce32c45dbd

@sudhanshu0603  resolved

**Comment by dev-adityapatel** [comment]
@sudhanshu0603  Issue resolved

**Comment by sudhanshu0603** [comment]
fixed
