### ISSUE TITLE
In address page, when we select the data by auto-suggestion then the add addresss button is not working

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/HSL-Home-page-design#16]
**Actual result:**
In address page, when we select the data by auto-suggestion then the add addresss button is not working.
https://www.hsldiamonds.com/account/addresses
https://www.loom.com/share/53dfe3e67c5f4de09864e08a147e2ff6
**Expected  result:**
By filling the form by auto-suggestin the fom should sumbit.

**Comment by dev-adityapatel** [comment]
@sudhanshu0603  It is working fine.

https://www.awesomescreenshot.com/video/10935976?key=3892742058592a4aab5c76e7b11afabc

**Comment by dev-adityapatel** [comment]
@sudhanshu0603  https://www.awesomescreenshot.com/video/11032090?key=06d2e76fde646c70fc57eadae636491c

It is working fine, also i checked it incognito mode

**Comment by sudhanshu0603** [comment]
@dev-adityapatel , it is now working.
https://www.loom.com/share/cd43a98494cb4667a83ded521043c16f

**Comment by sudhanshu0603** [comment]
working
