### ISSUE TITLE
The footer section, the title of Refund

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/HSL-Home-page-design#19]
**Actual result:**
![image](https://user-images.githubusercontent.com/102131636/188592047-037c28cc-cd11-4fb9-93e9-c682a07f6753.png)
![image](https://user-images.githubusercontent.com/102131636/188592123-c5e8516d-d8a3-476e-893d-e52a41fe5453.png)

**Expected result:**
The title needs to be Returns & Refund policy, we have a content for the return in the text content.
2: the url needed to be updated for the Returns & Refund Policy.
3: The title needs to be update for it.

**Comment by dev-adityapatel** [comment]
![image](https://user-images.githubusercontent.com/100192519/188652638-e1ea4df3-193e-4f22-8f09-e7d629bb384d.png)
![image](https://user-images.githubusercontent.com/100192519/188652703-93a0c791-f8e4-46ae-9dea-279c652bbadd.png)
@sudhanshu0603  Updated

**Comment by sudhanshu0603** [comment]
ok, resolved
