### ISSUE TITLE
In url the handle is given customer-order in the but in the header it is given Custom orders

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/HSL-Home-page-design#2]
**Actual result:**
In url the handle is given customer-order in the but in the header it is given Custom orders
![image](https://user-images.githubusercontent.com/102131636/188566347-d50fe8a6-9ae8-4dea-98dd-2d58aba97af1.png)
**Expected result:**
The naming convension needed to be verified.

**Comment by dev-adityapatel** [comment]
@sudhanshu0603  we nothing do here, it was already done on live site we just add here, I will confirm by client and update here

**Comment by dev-adityapatel** [comment]
@sudhanshu0603  resolved

**Comment by sudhanshu0603** [comment]
ok, resolved
