### ISSUE TITLE
The policy text needed to be in capitalize form.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/HSL-Home-page-design#20]
**Actual result:**
The text policy is coming in lowercase.
![image](https://user-images.githubusercontent.com/102131636/188592784-92623c04-beaf-4bd8-9dc4-634da31bd896.png)

**Expected result:**
The policy text needed to be in capitalize form.

**Comment by dev-adityapatel** [comment]
![image](https://user-images.githubusercontent.com/100192519/188650328-85ed86a9-9526-4842-b22b-f0f5c883b1ef.png)
@sudhanshu0603  resolved

**Comment by sudhanshu0603** [comment]
ok, resolved
