### ISSUE TITLE
In collection all, the images are not added.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/HSL-Home-page-design#22]
**Actual result:**
In collection all, the images are not added.
https://www.hsldiamonds.com/collections
![image](https://user-images.githubusercontent.com/102131636/188600457-3003f445-40d7-416d-ab8c-e5b7aa27ec9d.png)

**Expected result:**
The images needs to be add.

**Comment by ui-abhishekkushwaha** [comment]
it's depend upon client side

**Comment by sudhanshu0603** [comment]
ok
