### ISSUE TITLE
When we click on the cart icon on the product on the homepage then the loading bar is coming and it is breaking from the right side.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/HSL-Home-page-design#27]
**Actual result:**
When we click on the cart icon on the product on the homepage then the loading bar is coming and it is breaking from the right side.
![image](https://user-images.githubusercontent.com/102131636/188604439-64661280-49cb-4c1a-9d15-fbe2c7bd33c5.png)

**Expected result:**
The loader bar should not break from the right side of the product.

**Comment by ui-abhishekkushwaha** [comment]
@dev-adityapatel please check this issue

**Comment by dev-adityapatel** [comment]
@sudhanshu0603 issue resolved

**Comment by sudhanshu0603** [comment]
The cart icon is not clickable now, pls review @dev-adityapatel .
https://www.hsldiamonds.com/collections/mens-rings
![image](https://user-images.githubusercontent.com/102131636/189866976-6e85d4be-2c1a-4eaf-80ad-ecfe689d2a7c.png)

**Comment by dev-adityapatel** [comment]
@sudhanshu0603  Issue resolved

**Comment by sudhanshu0603** [comment]
ok, resolved
