### ISSUE TITLE
We can add some title for the instagram feed above the footer.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/HSL-Home-page-design#28]
**Actual result:**
We can add some title for the instagram feed above the footer.
![image](https://user-images.githubusercontent.com/102131636/188604973-7967199d-512d-4b19-8047-d8634ee0df97.png)

**Expected result:**
We can add some titles it will be better.

**Comment by dev-adityapatel** [comment]
![image](https://user-images.githubusercontent.com/100192519/188789879-b7f64df1-74aa-4d98-9636-681a3d7d563d.png)
@sudhanshu0603  Resolved

**Comment by sudhanshu0603** [comment]
ok, resolved
