### ISSUE TITLE
For the empty collections, we can add the continue shopping button it will be better and remove all the existing filters.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/HSL-Home-page-design#29]
**Actual result:**
For the empty collections, we can add the continue shopping button it will be better and remove all the existing filters.
https://www.hsldiamonds.com/collections/watches
![image](https://user-images.githubusercontent.com/102131636/188606295-20d196f2-a667-4601-b73e-4e674135820c.png)

**Expected result:**
The reference is attached below.
![image](https://user-images.githubusercontent.com/102131636/188606456-302f134d-83e2-4fd8-af52-e8037c585498.png)

**Comment by dev-adityapatel** [comment]
![image](https://user-images.githubusercontent.com/100192519/188645487-e0b96f03-f971-4b68-99be-a5bdb05a4d53.png)

@sudhanshu0603  it is done now, need to design it

**Comment by sudhanshu0603** [comment]
@dev-adityapatel , the sort by filters are coming pls review it.
![image](https://user-images.githubusercontent.com/102131636/189104169-14aaa871-a83a-42fc-96e2-c0ba782f09e2.png)
but for the reference it is not added.

we can add designed to the link of continue shopping it will be better, @ui-abhishekkushwaha , pls review it.

**Comment by dev-adityapatel** [comment]
@sudhanshu0603  Done

**Comment by dev-adityapatel** [comment]
![image](https://user-images.githubusercontent.com/100192519/189363466-71aa2057-c4b3-46c3-8491-ea0b7968fd04.png)

**Comment by sudhanshu0603** [comment]
ok, resolved
