### ISSUE TITLE
The text of the send button is coming of black colour.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/HSL-Home-page-design#3]
**Actual result:**
The text of the send button is coming of black colour.
![image](https://user-images.githubusercontent.com/102131636/188569434-b42c1242-9252-440e-b255-8ba53e2a7b68.png)
2: handle is coming of contact

**Expected result:**
1: The text of the send button should be of store colour combination.
2: the handle needs to be contact-us.

**Comment by dev-adityapatel** [comment]
2: the handle needs to be contact-us. : resolved
@sudhanshu0603  resolved

**Comment by sudhanshu0603** [comment]
ok, resolved
