### ISSUE TITLE
In collection page, the outofstock functionality is not working.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/HSL-Home-page-design#30]
**Actual result:**
When we select Instock and outofstock then only outofstock is selected then the only outofstock products have to show but all the products are coming.
When we select any filter and only soldout product are coming then the all the products are coming( sortby ) 
![image](https://user-images.githubusercontent.com/102131636/188607520-2b0f9ba7-a73b-4f2f-8662-32212ca07e5b.png)
**Expected result:**
The functionality have to work properly

**Comment by dev-adityapatel** [comment]
![image](https://user-images.githubusercontent.com/100192519/188636623-f11c4cdd-5689-4231-bcf7-c581e4399d78.png)
@sudhanshu0603  It is working fine

**Comment by sudhanshu0603** [comment]
https://www.loom.com/share/6267ee0fb4774d63b2cd9975603181cb
@dev-adityapatel  pls review the video and follow the steps,
for the designing part the for the first product the cart icon is disturbing  i have highted on the video pls review it, @ui-abhishekkushwaha .

**Comment by dev-adityapatel** [comment]
@sudhanshu0603  Resolved now

**Comment by sudhanshu0603** [comment]
resolved
