### ISSUE TITLE
The review are not added on the product page.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/HSL-Home-page-design#33]
**Actual result:**
The review are not added on the product page.
![image](https://user-images.githubusercontent.com/102131636/188613326-54a130b2-7652-4327-8bdc-61c03b0cf832.png)

**Expected result:**
We can add the review on the products page.

**Comment by dev-adityapatel** [comment]
![image](https://user-images.githubusercontent.com/100192519/188636341-f5d4b086-8d1a-4845-8890-99956a6cf99a.png)
![image](https://user-images.githubusercontent.com/100192519/188636380-fa2820a3-29c4-4fff-86c3-33fcb052a925.png)
@sudhanshu0603  Done

**Comment by dev-adityapatel** [comment]
@sudhanshu0603  it will show when any review will add no such as  additional functionality in free  app

**Comment by sudhanshu0603** [comment]
ok
