### ISSUE TITLE
In products page for the RELATED Products section, the cart icon is not coming.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/HSL-Home-page-design#34]
**Actual result:**
In products page for the RELATED Products section, the cart icon is not coming.
https://www.hsldiamonds.com/products/10k-3-40-3-44ct-d-mens-rings
![image](https://user-images.githubusercontent.com/102131636/188613876-7e286947-00a0-4b4e-a84a-941c582516e8.png)
2: The images are cropping.
![image](https://user-images.githubusercontent.com/102131636/188614305-e07a92fb-33d0-4239-890f-999cf1d38225.png)

**Expected result:**
The cart icon have to come on the related products section on the product page.
2: images should not be cropped.

**Comment by dev-adityapatel** [comment]
@sudhanshu0603  Resolved

![image](https://user-images.githubusercontent.com/100192519/188633782-21ce5f0d-aa61-440a-8733-5b58459bf49c.png)

**Comment by sudhanshu0603** [comment]
@ui-abhishekkushwaha , pls review the related products section, the cropping of the product, it was mention in the expecte result.
https://www.hsldiamonds.com/products/ced-test-product-do-not-purchase-copy-of-10k-0-20ct-d-earrings-lion-head?variant=43492165189874
![image](https://user-images.githubusercontent.com/102131636/189101996-3216565b-1a00-4334-a8bf-2fcc980bc990.png)

**Comment by sudhanshu0603** [comment]
ok, resolved
