### ISSUE TITLE
The main image in the cart page is not clickable

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/HSL-Home-page-design#35]
**Actual result:**
The main image in the cart page is not clickable.
https://www.hsldiamonds.com/cart
![image](https://user-images.githubusercontent.com/102131636/188615318-9e5d12c5-2859-47cb-ae76-29beaf3a10c8.png)

**Expected result:**
The image have to be clickable.

**Comment by dev-adityapatel** [comment]
@sudhanshu0603  It is css Issue

![image](https://user-images.githubusercontent.com/100192519/188630896-56753f4f-d032-4636-9aa3-22fc64b7d40f.png)

**Comment by sudhanshu0603** [comment]
ok, resolved
