### ISSUE TITLE
For the home page, collection page, the when we open the quick view then the quick view form page is not scrolling.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/HSL-Home-page-design#39]
**Actual result:**
For the home page, collection page, the when we open the quick view then the quick view form page is not scrolling.
![image](https://user-images.githubusercontent.com/102131636/188792371-fc27fa72-d6ed-4849-942b-1ce87eff9d40.png)

**Expected result:**
When we open the quick view,then the quick view page have to work on scrolling.

**Comment by dev-adityapatel** [comment]
@sudhanshu0603  it is css issue, it is working when window width grater than 749px

**Comment by sudhanshu0603** [comment]
ok,
