### ISSUE TITLE
When we click on the book an appointment, then the wishlist icon is coming while loading the page and its is taking much time.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/HSL-Home-page-design#4]
**Actual result:**
When we click on the book an appointment, then the wishlist icon is coming while loading the page and its is taking much time.
https://www.loom.com/share/bbfbe65b8b244686b421884d6ed8c3f2 
**Expected result:**
The wishlist icon should not come while loading the page and loading speed can be incresed.

**Comment by dev-adityapatel** [comment]
@sudhanshu0603  Wish-list are not required for this so that why it is removed

**Comment by sudhanshu0603** [comment]
@dev-adityapatel need discussion ,

**Comment by dev-adityapatel** [comment]
@sudhanshu0603  no need here to show wishlist button so whenever it get loaded we remove this
