### ISSUE TITLE
The trusted site icon is coming to the right side of the footer.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/HSL-Home-page-design#44]
**Actual result:**
The trusted site icon is coming to the right side of the footer.
![image](https://user-images.githubusercontent.com/102131636/188799490-e68ded6b-0d0c-473a-a3b0-77e1431f51b8.png)
**Expected result:**
The  trusted site branding is coming to the right side, if it is of no use we can remove it.

**Comment by dev-adityapatel** [comment]
@sudhanshu0603  Not Required

**Comment by sudhanshu0603** [comment]
ok,
