### ISSUE TITLE
For mobile view, only 2 images are visible on the instagram feed, but many images are added.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/HSL-Home-page-design#45]
**Actual result:**
For mobile view, only 2 images are visible on the instagram feed, but many images are added.
![image](https://user-images.githubusercontent.com/102131636/188801097-5e08eddd-5e64-422b-bfcf-dcccc83ade2e.png)

**Expected result:**
The images should be in sliding then it will be possible to show all the images in mobile view.

**Comment by dev-adityapatel** [comment]
@sudhanshu0603  No addition setting are provided in free plan, So we can not customised it

**Comment by sudhanshu0603** [comment]
ok, then
