### ISSUE TITLE
Book an appointment page in the header.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/HSL-Home-page-design#5]
**Actual result:**
1: The cross symbol is missing for closing the form.
![image](https://user-images.githubusercontent.com/102131636/188571822-291fa364-2beb-488a-aafd-aef1d8395b74.png)
2: The text of the book now is not related to the store colour combination.
3: The error message is not coming of red colour.
4: the validations are missing. 
![image](https://user-images.githubusercontent.com/102131636/188572188-1464073e-db58-4a77-955e-fd5389e5802a.png)

**Expected result:**
1: we can add the cross symbol for closing the form. ( suggestion)
2: the text of the book now needs to be improved.
3: The error message needs to be of red colour.
4: validation can be added for the form.( suggestion if it is not coming from the app)

**Comment by dev-adityapatel** [comment]
@sudhanshu0603  this form embedding by app ,we can not customise it

**Comment by sudhanshu0603** [comment]
@ui-abhishekkushwaha , pls review the points added , of designing if they are feasible , we can implement it.

**Comment by ui-abhishekkushwaha** [comment]
all issues which can possible has done complete from my side

**Comment by sudhanshu0603** [comment]
ok, resolved
