### ISSUE TITLE
For the very first time, when we type digit then the search bar border is breaking.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/HSL-Home-page-design#56]
**Actual result:**
For the very first time, when we type digit then the search bar border is breaking.
![image](https://user-images.githubusercontent.com/102131636/188810515-6579e843-9d52-40cf-a886-c798a870a564.png)
**Expected result:**
The search bar border should not break.

**Comment by sudhanshu0603** [comment]
![image](https://user-images.githubusercontent.com/102131636/189090376-5de0199e-3bf2-4276-9eec-862fd198385f.png)
@ui-abhishekkushwaha ,
pls review the search bar , the background is coming on it.

**Comment by ui-abhishekkushwaha** [comment]
![image](https://user-images.githubusercontent.com/95025218/189092022-8634d8c9-ee53-45b4-b2f9-dd73fc6b6116.png)
check this one

**Comment by sudhanshu0603** [comment]
https://www.loom.com/share/cddb629d278f4f73950bfaf7fa88dfef,

It is coming pls review the video..

**Comment by sudhanshu0603** [comment]
ok, resolved
