### ISSUE TITLE
The validation are missing.( suggestion )

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/HSL-Home-page-design#7]
**Actual result:**
The validation are missing.( suggestion )
https://www.hsldiamonds.com/pages/customer-order
![image](https://user-images.githubusercontent.com/102131636/188577664-bb955b8e-1845-4975-bef4-5e76aa2ad1ac.png)

**Expected result:**
We can add the validation.

**Comment by dev-adityapatel** [comment]
@sudhanshu0603  Not required, this is coming from app site

**Comment by sudhanshu0603** [comment]
ok, resolved
