### ISSUE TITLE
Without login the wishlist icon is adding the product to the wishlist.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/HSL-Home-page-design#8]
**Actual result:**
Without login the wishlist icon is adding the product to the wishlist.
![image](https://user-images.githubusercontent.com/102131636/188578497-62fdcc8d-156f-45aa-a015-6be992181e26.png)

**Expected result:**
Without successfull login, when we click on the wishlist then the login button have to come in wishlist page.

**Comment by dev-adityapatel** [comment]
@sudhanshu0603  resolved

**Comment by sudhanshu0603** [comment]
ok, resolved
